#!/bin/sh


roslaunch seven_dof_arm_gazebo seven_dof_arm_gazebo_control.launch &
rostopic pub /seven_dof_arm/joint4_position_controller/command std_msgs/Float64 1.0
#i get error here rostopic echo /seven_dof_arm/joint_states

